#开发环境配置文件
spring:
  application:
    name: dioxide-service-one

server:
  port: 8768
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/